sudo: required
dist: trusty

language: node_js
node_js: "10"

matrix:
  include:
    - name: "macOS"
      os: osx

    - name: "Windows"
      os: windows

    - name: "Linux"
      os: linux


cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install yarn@latest -g

script:
  - quasar build -m electron

